### ISSUE TITLE
label slot for children nodes not working

### ISSUE THREAD

**Issue by dinhtq** [suusan2go/vuetify-draggable-treeview#105]
It seems like the prepend slot works for children nodes, but label slot for children nodes are not showing. Any ideas why?

**Comment by suusan2go** [comment]
Label slot for children nodes seems to work well in the demo app.
https://github.com/suusan2go/vuetify-draggable-treeview/blob/4eb2295e9eaba208d697aaf4d993da093037228e/demo/src/components/HelloWorld.vue#L60-L62
Can you give me some example code or repository to reproduce your issue?

**Comment by hossein-git** [comment]
Hi;
i have same issue ,
 in demo ,label slot for children node does not work too.
<img width="539" alt="child-node" src="https://user-images.githubusercontent.com/46167021/88714220-b6e0a600-d131-11ea-874a-d726a8159aa6.png">

**Comment by Steveiwonder** [comment]
I also have this same issue.
 <VuetifyDraggableTreeview v-model="items">
          <template v-slot:label="{item}">{{item.name}} [TEST]</template>
        </VuetifyDraggableTreeview>

All top level elements have [TEST] appended, but any child elements do not

**Comment by suusan2go** [comment]
@Steveiwonder Thank you for your detailed report. I'll fix this soon.

**Comment by suusan2go** [comment]
this has been fixed and released as version 0.0.5. Thank you for your report 🍻
