### ISSUE TITLE
With Vuetify 2.2 the alignment of children is working differently

### ISSUE THREAD

**Issue by lambertbeekhuis** [suusan2go/vuetify-draggable-treeview#188]
Vuetify 2.2 introduced the commit https://github.com/vuetifyjs/vuetify/commit/6e368edf57455d20a0d8c19945ee831bb9b24ca8

which changes the alignment. Therefor, this component does not align correctly anymore from Vuetify 2.2 and onwards.

**Comment by Doclassif** [comment]
How to fix?

**Comment by lambertbeekhuis** [comment]
I made another repo, the basics are working, but had to find out quite some stuff to pubish an npm-package. 

See https://github.com/lambertbeekhuis/v-treeview-draggable
