### ISSUE TITLE
How to get the moved item and the item that was moved?

### ISSUE THREAD

**Issue by Doclassif** [suusan2go/vuetify-draggable-treeview#212]
Or rather, I need the id of two items.
How to use input event? How to get an array?

**Comment by suusan2go** [comment]
What you get from the input event is just the value of the entire updated array.
For example, if you passed `value` props like below and moved second item to first, you would be get the value like this from input event.
```js
// props value
[{ id: 1, name: "one"},  {id: 2, name: "two"} ]
// from input event
[{ id: 2, name: "two"}, {id: 1, name: "one"} ]
```
