### ISSUE TITLE
Looking bad after build

### ISSUE THREAD

**Issue by elihaidv** [suusan2go/vuetify-draggable-treeview#389]
Hi.
When I use `npm run serve` It works well.
But with `npm run build` It looking bad.

While serving:
![image](https://user-images.githubusercontent.com/11449032/92130876-e740f180-ee0d-11ea-9abf-25b1f0c451d2.png)

After build:
![image](https://user-images.githubusercontent.com/11449032/92130806-d3958b00-ee0d-11ea-9a64-5a68461dc6cf.png)

My Code:
```    
<v-draggable-treeview
  group="test"
  v-model="items"
></v-draggable-treeview>
```
Data Section:
```
items: [{ id: 1, name: "hoge", children: [{ id:11, name: "hoge-child1" }] }]
```

**Comment by suusan2go** [comment]
@elihaidv Can you share a minimum repository to reproduce your issue?

**Comment by elihaidv** [comment]
Finally I have figure it out!
Just adding
```
import "vuetify/dist/vuetify.css";
```
in my `main.js`

Maby it will be good idea to put it in readme
